sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FMeA+SeF3TJATegTFd1UqciajN6L06KoTYBXdUKsd6mTzqcjHIyZegCbT+3YIyrwU1UgB3BbQdY/6qPcAYAeHITgmTxYnmivMMq1ZPiVtc39A7CDsKD1QEp1suos0nf/NhR+LioBgfFmBJY214jZSv0wgTJO7i4CarKoJzdwUaOgPlOqji/Qz2pxe1Pefa7R4kR/oHYXru6kaurKGw7otZ7IE+6VJFdyKEwGqQMNq+89o5id9DHNFmhJeNESfYi3GjtIxo/jymgEzpNS9vZdJ9lnpxtS8ac9GmmKs5r3fYOJ6XJuc4xp2qOJd5cwfPb0ipxlEuiP7u0Q3Jvy7RpzFpcZWrefwUiynUhqq5na7KazjzoXqgoT3U5cOR97h0H1s/dqZAVxkUmn0+MGqBf60zcwKNHLBDp8OB5znxzpQm0uQWZMw70STgKnVfR8JVoSBEmSFG+XdGb8vRQb4caDay6MqXFSffLjbMu3rBRp8zsDr0SYXGL8du4JSiSp4qDu2KMrcyz7bAccdH5KCjpXKm0vqaL+r73Ms3LPv9VvlKI17vU3xdokuwthRZtgsPyM0FHep9fJ5e2A0LxIyyt+cKaICx+Csua84kW879KapBMzpcizXoIBa0qbaq+iict+Y/FwFiKgMVZsMVXv+JQKkyGLSR8I04rupv9JbD3lkvI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Twice-Told-Tales_508
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy